FROM golang:1.17-bullseye

RUN apt update && apt install -y  build-essential \
    libalut-dev \
    libasound2-dev \
    libc6-dev \
    libgl1-mesa-dev \
    libglu1-mesa-dev \
    libxcursor-dev \
    libxi-dev \
    libxinerama-dev \
    libxrandr-dev \
    libxxf86vm-dev \
    mesa-utils \
    pkg-config \
    xorg-dev \
    xvfb
